---
{{- range .Values.ns_users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }} : {{ $value }}
    {{- end }}
  name: {{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if .default_role }}
  name: {{ .default_role }}
{{- else }}
  name: {{ .name }}
{{- end }}
subjects:
- kind: {{ .kind }}
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}