{{- range .Values.roles }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 
  name: {{ .name }}
  namespace: {{ .namespace }}
rules:
{{ toYaml .rules }}
{{- end }}
{{- end }}