{{- range .Values.ns_users }}
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: {{ .name }}-csr
spec:
  groups:
    - system:authenticated
  request: {{ $.Files.Get (printf "csr/%s.csr" .name) | b64enc | trim }}
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
{{- end}}
