{{- range .Values.cluster_roles }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 
  name: {{ .name }}
rules: 
{{ toYaml .rules }}
{{- end }}
{{- end }}