---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{- range $key, $value := .Values.user_role.labels }}
    {{ $key }} : {{ $value }}
    {{- end }}
  name: {{ .Values.user_role.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.user_role.name }}
subjects:
- kind: {{ .Values.user_role.kind }}
  name: {{ include "k8s_user.serviceAccountName" . }}
  namespace: {{ .Values.user_namespace1.name }}