{{- range .Values.role_binding }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }} : {{ $value }}
    {{- end }}
  name: {{ .name }}
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if .default_role }}
  name: {{ .default_role }}
{{- else }}
  name: {{ .rolename }}
{{- end }}
subjects:
- kind: {{ .kind }}
  name: {{ .username }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}