---
{{- range .Values.ns_users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 
  name: {{ .name }}
  namespace: {{ .namespace }}
rules: {{ include "k8s_user.roles" . }}
{{- end }}
