---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  {{- range $key, $value := .Values.ns_admin_cluster_role.labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 
  name: {{ .Values.ns_admin_cluster_role.name }}
rules: {{ include "k8s_user.clusterRoles" . }}
