---
#k8s cert-manager issuer CRD name 
issuer_name: echo.example.com-issuer

#k8s cert-manager certificate CRD name 
cert_name: echo.example.com-cert

#k8s secret name used by ingress
secret_name: echo-example-com-tls

#a common name to be used on the Certificate.
server_name: echo.example.com

#a list of DNS subjectAltNames to be set on the Certificate.
dns_server_name: echo.example.com

#name of helm release
chart_name: echo-app

#KUBECONFIG
k8s_kubeconfig: /home/cluster01/.kube/admin.conf

# Vault pki policy name.
pki_policy_name: example-dot-com

#K8s auth role name for vault access
k8s_auth_role_name: issuer

#K8s ServiceAccount name used for access to vault
k8s_sa_name: issuer

#k8s app namespace
k8s_namespace: namespace1

#Vault pki role name. 
pki_role: "{{ pki_policy_name }}"

#Domain name used for certificate generation
domain_name: "example.com"

#Allowing subdomain in certificate
allow_subdomains: "true"

#Maximum certificate ttl
max_cert_ttl: "15m"