elastic_operator_version: "1.6.0"
# Namespace for elastic-operator deploy
elastic_namespace: elastic-operator
# Elastic Operator pod toleration
elastic_operator_taint: node-role.kubernetes.io/worker

elastic_version: "7.10.0"
#Elasticsearch and kibana pod toleration
elastic_app_taint: node-role.kubernetes.io/worker
# Elasticsearch CRD name
elastic_name: elasticsearch
# Kibana CRD name
kibana_name: kibana
#Kibana instance number
kibana_count: 1
#Elasticsearch instance number
elastic_count: 1
# Elasticsearch and Kibana pod toleration
logging_namespace: logging

#Kibana ingress name
kibana_ingress_name: kibana-ingress

#Kibana hostname
kibana_host: kibana.example.com

#Kibana Ingress TLS secret name
kibana_tls_secret_name: echo-example-com-tls

#Kibana k8s service name
kibana_service_name: "{{ kibana_name }}-kb-http"

#Fluentbit pod toleration
fluentbit_toleration:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/gw
    effect: NoSchedule
  - key: node-role.kubernetes.io/worker
    effect: NoSchedu  

# Fluentbit config
fluentbit_service: |
  [SERVICE]
      Flush 1
      Daemon Off
      Log_Level info
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port {{ '{{' }} .Values.service.port {{ '}}' }}

## https://docs.fluentbit.io/manual/pipeline/inputs
fluentbit_input: |
  [INPUT]
      Name tail
      Path /var/log/containers/*.log
      Parser containerd
      Tag kube.*
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On

  [INPUT]
      Name systemd
      Tag host.*
      Read_From_Tail On

## https://docs.fluentbit.io/manual/pipeline/filters
fluentbit_filter: |
  [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
## https://docs.fluentbit.io/manual/pipeline/outputs
fluentbit_output: |
  [OUTPUT]
      Name es
      Match kube.*
      Host {{ elastic_name }}-es-http.{{ logging_namespace }}.svc
      HTTP_User elastic
      HTTP_Passwd {{ elastic_pass.stdout }}
      tls             On
      tls.verify      Off
      Logstash_Format On
      Retry_Limit False
      Trace_Error On
      Replace_Dots On

  [OUTPUT]
      Name es
      Match host.*
      Host {{ elastic_name }}-es-http.{{ logging_namespace }}.svc
      HTTP_User elastic
      HTTP_Passwd {{ elastic_pass.stdout }}
      tls             On
      tls.verify      Off
      Logstash_Format On
      Logstash_Prefix node
      Retry_Limit False
      Trace_Error On
      Replace_Dots On
## https://docs.fluentbit.io/manual/pipeline/parsers
fluentbit_customParsers: |
  [PARSER]
      Name docker_no_time
      Format json
      Time_Keep Off
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L

  [PARSER]
      Name   nginx_custom
      Format regex
      Regex (?<remote_addr>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<request>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S %z
      
  [PARSER]
      Name   echo_app_parser
      Format regex
      Regex (?<log_time>[^\]]*) (?<servername>[^ ]*) (?<remote_addr>[^ ]*) "(?<method>\S+) (?<request>[^\"]*)" (?<code>[^ ]*) (?<size>[^ ]*) "(?<agent>[^\"]*)" (?<duration>[^ ]*)
      Time_Key log_time
      Time_Format %Y/%m/%d %H:%M:%S 

  [PARSER]
      Name        syslog
      Format      regex
      Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key    time
      Time_Format %b %d %H:%M:%S

  [PARSER]
      Name containerd
      Format regex
      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
      Time_Keep On
