---
elastic_operator_version: "1.6.0"
elastic_namespace: elastic-operator
elastic_operator_taint: node-role.kubernetes.io/worker
elastic_version: "7.10.0"
elastic_app_taint: node-role.kubernetes.io/gw
elastic_name: elasticsearch
kibana_name: kibana
kibana_count: 1
elastic_count: 1
logging_namespace: logging


fluentbit_service: |
  [SERVICE]
      Flush 1
      Daemon Off
      Log_Level info
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port {{ .Values.service.port }}

fluentbit_inputs: |
  [INPUT]
      Name tail
      Path /var/log/containers/*.log
      Parser docker
      Tag kube.*
      Mem_Buf_Limit 5MB
    Skip_Long_Lines On

  [INPUT]
      Name systemd
      Tag host.*
      Read_From_Tail On

fluentbit_filter: |
  [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On

fluentbit_output: |
  [OUTPUT]
      Name es
      Match kube.*
      Host minikube-logging-es-http.logging.svc
      HTTP_User elastic
      HTTP_Passwd dw1S9KvO13Y355Z3BDytGZ67
      tls             On
      tls.verify      Off
      Logstash_Format On
      Retry_Limit False
      Trace_Error On
      Replace_Dots On

  [OUTPUT]
      Name es
      Match host.*
      Host minikube-logging-es-http.logging.svc
      HTTP_User elastic
      HTTP_Passwd dw1S9KvO13Y355Z3BDytGZ67
      tls             On
      tls.verify      Off
      Logstash_Format On
      Logstash_Prefix node
      Retry_Limit False
      Trace_Error On
      Replace_Dots On

fluentbit_customParsers: |
  [PARSER]
      Name docker_no_time
      Format json
      Time_Keep Off
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L

  [PARSER]
      Name   nginx_custom
      Format regex
      Regex (?<remote_addr>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<request>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S %z
      
    [PARSER]
        Name   echo_app_parser
        Format regex
        Regex (?<log_time>[^\]]*) (?<servername>[^ ]*) (?<remote_addr>[^ ]*) "(?<method>\S+) (?<request>[^\"]*)" (?<code>[^ ]*) (?<size>[^ ]*) "(?<agent>[^\"]*)" (?<duration>[^ ]*)
        Time_Key log_time
        Time_Format %Y/%m/%d %H:%M:%S   