all:
  children:
    k8s_ha_masters:
      hosts:
        master[1:3]:
    k8s_ha_workers:
      hosts:
        worker[1:3]:
    k8s_ha_gateway:
      hosts:
        gw[1:2]:
    k8s_ha_cluster:
      children:
        k8s_ha_masters:
        k8s_ha_workers:
        k8s_ha_gateway:
    k8s_ha_not_masters:
      children:
        k8s_ha_gateway:
        k8s_ha_workers: