---
- name: Create echo-app vault init bash script
  template:
    dest: /tmp/app-vault-init.sh
    src: app-vault-init.sh.j2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0555

- name: Copy file to pod
  shell: kubectl cp /tmp/app-vault-init.sh vault-0:/tmp/app-vault-init.sh -n vault

- name: Delete tmp file
  file:
    dest: /tmp/app-vault-init.sh
    state: absent

- name: Execute echo-app vault init script
  shell: kubectl exec vault-0 -n vault -- /bin/sh -c "/tmp/app-vault-init.sh"
  register: vault_init_script_result