
---
- name: Deploy echo app chart inside namespace1 namespace
  community.kubernetes.helm:
    name: "{{ chart_name }}"
    chart_ref: Helm/echo-app
    release_namespace: "{{ k8s_namespace}}"
    create_namespace: yes
    force: yes

#- name: Wait for vault pods become ready
#  shell: "kubectl wait --namespace={{ k8s_namespace }} --for=condition=Ready --all pods --timeout=60s"
#  register: vault_ready

- name: Get Token of service account
  shell: 'kubectl get serviceaccount {{ k8s_sa_name }} -n {{ k8s_namespace }} -o json | jq -r ".secrets[].name"'
  register: issuer_sa_token

- name: Put sa token in variable
  set_fact:
    ISSUER_SECRET_REF: "{{ issuer_sa_token.stdout }}"

- name: Debug token
  debug:
    var: ISSUER_SECRET_REF
    
- name: Deploy Issuer
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: cert-manager.io/v1alpha2
      kind: Issuer
      metadata:
        name: "{{ issuer_name }}"
        namespace: "{{ k8s_namespace }}"
      spec:
        vault:
          server: http://vault.vault
          path: pki/sign/{{ pki_role }}
          auth:
            kubernetes:      
              mountPath: /v1/auth/kubernetes
              role: "{{ k8s_sa_name }}"
              secretRef:
                name: "{{ ISSUER_SECRET_REF }}"
                key: token      

- name: Deploy Certificate
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: cert-manager.io/v1alpha2
      kind: Certificate
      metadata:
        name: "{{ cert_name }}"
        namespace: "{{ k8s_namespace }}"
      spec:
        secretName: "{{ secret_name }}"
        issuerRef:
          name: "{{ issuer_name }}"
        commonName: "{{ server_name }}"
        dnsNames:
        - "{{ server_name }}"    
