apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: test-application
  name: namespace1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-app
  namespace: namespace1
spec:
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
      - name: banana
        image: hashicorp/http-echo
        args:
          - "-text=banana"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/worker

---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-banana-service
  namespace: namespace1
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-app
  namespace: namespace1
  labels:
    app: apple
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
      - name: apple
        image: hashicorp/http-echo
        args:
          - "-text=apple"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/worker

---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-apple-service
  namespace: namespace1
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: echo-app-ingress
#  namespace: namespace1
#  annotations:
#    ingress.kubernetes.io/rewrite-target: /
#spec:
#  tls:
#  - hosts:
#      - "echo.example.com"
#    secretName: echo-example-com-tls
#  rules:
#  - host: "echo.example.com"
#    http:
#      paths:
#        - path: /apple
#          pathType: Prefix
#          backend:
#            service:
#              name: echo-app-apple-service
#              port: 
#                number: 5678
#        - path: /banana
#          pathType: Prefix
#          backend:
#            service:
#              name: echo-app-banana-service
#              port: 
#                number: 5678
