- hosts: localhost
  #become: yes
  gather_facts: yes

  pre_tasks:
    # - name: Add taints to gw nodes
    #   command: kubectl taint nodes {{ node }} {{ kubernetes_gw_taints }}
    #   loop: "{{ groups['k8s_ha_gateway'] }}"
    #   loop_control:
    #     loop_var: node
    #   when: kubernetes_role == 'first-master'

    # - name: Add taints to worker nodes
    #   command: kubectl taint nodes {{ node }} {{ kubernetes_worker_taints }}
    #   loop: "{{ groups['k8s_ha_workers'] }}"
    #   loop_control:
    #     loop_var: node
    #   when: kubernetes_role == 'first-master'
      
    # - name: Install nessesary package
    #   block:
    #     - name: Install pip
    #       apt:
    #         name: python3-pip
    #         state: present
    #         update_cache: yes
        
    #     - name: Install openshift
    #       pip:
    #         name: openshift
    #   when: kubernetes_role == 'first-master'
  tasks:
    - name: Change k8s api port to k8s VIP port
      lineinfile:
        path: ~/.kube/admin.conf
        regexp: '(^\s*server:\s*){{ item.search }}$'
        line:  '\1{{ item.replace }}'
        backrefs: yes
      loop:
      - { search: 'https://k8s-cp:8443', replace: 'https://k8s-cp:6443' }
    

  roles:
    # - { role: role-k8s_manifests, when: kubernetes_role == 'first-master'}
    # - { role: role-helm, when: kubernetes_role == 'first-master'}
    # - { role: role-ingress, when: kubernetes_role == 'first-master'}
    # - { role: role-vault, when: kubernetes_role == 'first-master' }
    # - { role: role-certmanager, when: kubernetes_role == 'first-master' }
    # - { role: role-app-deploy, when: kubernetes_role == 'first-master'}
    # - { role: role-k8s-ns-users} #, when: kubernetes_role == 'first-master'}
