---
- name: Add Elastic operator chart repo
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Update helm repo
  command: helm repo update

- name: Deploy elastic chart inside {{ elastic_namespace }} namespace with values
  community.kubernetes.helm:
    name: elastic-operator
    chart_ref: elastic/eck-operator
    release_namespace: elastic_namespace
    create_namespace: yes
    force: yes
    values:
      installCRDs: true
      replicaCount: 1
      tolerations:
        - key: "{{ elastic_operator_taint }}"
          effect: NoSchedule
      podMonitor:
        enabled: true
        namespace: monitoring
        labels:
          release: monitoring
          app: kube-prometheus-stack
      config:
        metricsPort: 8088

        