---
- name: Add Elastic operator chart repo
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Update helm repo
  command: helm repo update

- name: Deploy elastic chart inside {{ elastic_namespace }} namespace with values
  community.kubernetes.helm:
    name: elastic-operator
    chart_ref: elastic/eck-operator
    release_namespace: elastic_namespace
    create_namespace: yes
    force: yes
    values:
      installCRDs: true
      replicaCount: 1
      tolerations:
        - key: "{{ elastic_operator_taint }}"
          effect: NoSchedule
      podMonitor:
        enabled: true
        namespace: monitoring
        labels:
          release: monitoring
          app: kube-prometheus-stack
      config:
        metricsPort: 8088

- name: Deploy Elasticsearch
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Elasticsearch
      metadata:
        name: "{{ elastic_name }}"
      spec:
        version: "{{ elastic_version }}"
        nodeSets:
        - name: default
          count: "{{ elastic_count }}"
          config:
            node.master: true
            node.data: true
            node.ingest: true
            node.store.allow_mmap: false
          podTemplate:
            spec:
              tolerations:
                - effect: NoSchedule
                  key: {{ elastic_app_taint }}

- name: Deploy Kibana
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: kibana.k8s.elastic.co/v1
      kind: Kibana
      metadata:
        name: "{{ kibana_name }}"
      spec:
        version: "{{ elastic_version }}"
        count: "{{ kibana_count }}"
        elasticsearchRef:
          name: "{{ elastic_name }}"
        podTemplate:
          spec:
            tolerations:
              - effect: NoSchedule
                key: {{ elastic_app_taint }}
