- name: Add cert-manager chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Update helm repo
  command: helm repo update

- name: Deploy cert-manager chart inside cert-manager namespace with values
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    force: yes
    values:
      prometheus:
        enabled: true
        servicemonitor:
          enabled: true
          namespace: "{{ prometheus_stack_namespace }}"
          prometheusInstance: "{{ prometheus_stack_release_name }}"
          targetPort: 9402
          path: /metrics
          interval: 60s
          scrapeTimeout: 30s
          labels: {}
      installCRDs: true
      replicaCount: 3
      tolerations:
        - key: "{{ cert_manager_taint }}"
          effect: NoSchedule
      webhook:
        replicaCount: 2
        tolerations:
          - key: "{{ cert_manager_taint }}"
            effect: NoSchedule
      cainjector:
        replicaCount: 2
        tolerations:
          - key: "{{ cert_manager_taint }}"
            effect: NoSchedule  

- name: Wait for cert-manager pods become ready
  shell: "kubectl wait --namespace=cert-manager --for=condition=Ready --all pods --timeout=600s"