- name: Add cert-manager chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Update helm repo
  command: helm repo update

- name: Deploy cert-manager chart inside cert-manager namespace with values
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    force: yes
    values:
      installCRDs: true
      replicaCount: 3
      tolerations:
        - key: node-role.kubernetes.io/gw
          effect: NoSchedule
      webhook:
        replicaCount: 2
        tolerations:
          - key: node-role.kubernetes.io/gw
            effect: NoSchedule
      cainjector:
        replicaCount: 2
        tolerations:
          - key: node-role.kubernetes.io/gw
            effect: NoSchedule  

- name: Wait for vault pods become ready
  shell: "kubectl wait --namespace=cert-manager --for=condition=Ready --all pods --timeout=60s"
  register: vault_ready

- name: Create issuer SA
  community.kubernetes.k8s:
    name: "{{ k8s_sa_name }}"
    api_version: v1
    kind: ServiceAccount
    namespace: "{{ k8s_namespace }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"

- name: Pause for 1 minutes for cert-manager sign his certificate
  pause:
    minutes: "1"
    prompt: "Wait for Cert-manager become ready"
