- name: Add cert-manager chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Update helm repo
  command: helm repo update

- name: Deploy cert-manager chart inside cert-manager namespace with values
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    force: yes
    values:
      installCRDs: true
      replicaCount: 3
      tolerations:
        - key: node-role.kubernetes.io/worker
          effect: NoSchedule
      webhook:
        replicaCount: 2
        tolerations:
          - key: node-role.kubernetes.io/worker
            effect: NoSchedule
      cainjector:
        replicaCount: 2
        tolerations:
          - key: node-role.kubernetes.io/worker
            effect: NoSchedule  

- name: Wait for vault pods become ready
  shell: "kubectl wait --namespace=cert-manager --for=condition=Ready --all pods --timeout=60s"
  register: vault_ready