apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-app1.fullname" . }}-service
  labels:
    {{- include "echo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app1_name}}
spec:
  type: {{ .Values.service_app1.type }}
  ports:
    - port: {{ .Values.service_app1.port }}
  selector:
    {{- include "echo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app1_name}}
