{{- range $i, $hosts := .Values.ingress.hosts -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .host }}-cert
spec:
  secretName: {{ (index $.Values.ingress.tls $i).secretName }}
  issuerRef:
    name: {{ .host }}-issuer
  commonName: {{ $hosts.host }}
  dnsNames:
  - {{ $hosts.host }}   
{{- end }}