ansible_python_interpreter: /usr/bin/python3
# '{{ ansible_playbook_python }}'

k8s_cp: "192.168.1.131"
#k8s_cp: "192.168.1.150"
k8s_cp_port: 8443
kube_vip_address: "192.168.1.150"

kubernetes_kubeadm_init_extra_opts: "--cri-socket  /run/containerd/containerd.sock"
used_eth_interface: "eth1"

kubernetes_gw_taints: node-role.kubernetes.io/gw:NoSchedule
kubernetes_worker_taints: node-role.kubernetes.io/worker:NoSchedule