ansible_python_interpreter: /usr/bin/python3


k8s_cp: "192.168.1.131"
#k8s_cp: "192.168.1.150"
k8s_cp_port: 8443
kube_vip_address: "192.168.1.150"

kubernetes_kubeadm_init_extra_opts: "--cri-socket  /run/containerd/containerd.sock"
used_eth_interface: "eth1"
