---
#Vault pod names for unseal
vault_pod_names:
  - vault-1
  - vault-2

# KUBECONFIG
k8s_kubeconfig: /home/{{ ansible_user }}/.kube/admin.conf

#Root Certificate Authority name
root_ca_name: "Demo Root Certificate Authority"

#Root Certificate Authority certificate filename
root_ca_cert_filename: "demo-root-ca"
