---
#Vault pod names for unseal
vault_pod_names:
  - vault-0
#  - vault-1
#  - vault-2

k8s_kubeconfig: /home/cluster01/.kube/admin.conf

#Root Certificate Authority name
root_ca_name: "Demo Root Certificate Authority"

#Root Certificate Authority certificate filename
root_ca_cert_filename: "demo-root-ca"

localhost_user: cluster01


