---
- name: Create vault init bash script
  template:
    dest: /tmp/vault_init.sh
    src: vault_init.sh.j2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0555
 
- name: Copy file to pod
  shell: kubectl cp /tmp/vault_init.sh vault-0:/tmp/vault_init.sh -n vault

- name: Delete tmp file
  file:
    dest: /tmp/vault_init.sh
    state: absent
 
- name: Execute vault init script
  shell: kubectl exec vault-0 -n vault -- /bin/sh -c "/tmp/vault_init.sh"
  register: vault_init_script_result

- name: Get Vault root CA cert to ansible executor host
  command: "kubectl cp vault/vault-0:/tmp/{{ root_ca_cert_filename }}.json /tmp/{{ root_ca_cert_filename }}.json"
  when: vault_init_script_result.stdout.find("Success!") != -1

- name: Fetch Vault root CA cert to ansible host
  fetch:
    src: /tmp/{{ root_ca_cert_filename }}.json
    dest: /home/{{ username_on_the_host.stdout }}/
    flat: yes

- name: Set Vault root CA cert mode
  file: 
    path: /home/{{ username_on_the_host.stdout }}/{{ root_ca_cert_filename }}.json
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: 0400
  delegate_to: localhost

- name: Delete Vault root CA cert from ansible executor
  file:
    path: /tmp/{{ root_ca_cert_filename }}.json
    state: absent