---
- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host
  changed_when: false

- name: Set local path provisioner as default storage class
  shell: > 
    kubectl patch storageclass local-path
    -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

- name: Add Vault chart repo
  community.kubernetes.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Update helm repo
  command: helm repo update

- name: Deploy Vault chart inside Vault namespace with values
  community.kubernetes.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: vault
    create_namespace: yes
    force: yes
    values:
      injector:
        tolerations: |
          - key: node-role.kubernetes.io/worker
            effect: NoSchedule
      server:
        tolerations: |
          - key: node-role.kubernetes.io/worker
            effect: NoSchedule
        ha:
          enabled: true
          replicas: 3
          raft:
            enabled: true

- name: Pause for 60 seconds for vault images downloaded and started
  pause:
    seconds: "60"
    prompt: "Wait for Helm release is initialized"

- name: Wait for vault pods become ready
  shell: "kubectl wait --namespace=vault --for=condition=Initialized pod/vault-0 --timeout=600s"
  register: vault_ready

- include_tasks: prepare.yml

- include_tasks: unseal_main_pod.yml

- include_tasks: init.yml
