---
- name: Pause for 100 seconds for pv bound
  pause:
    seconds: "100"
    prompt: "Wait for vault pv become bound"

- name: Init vault operator
  shell: "kubectl exec vault-0 -n vault -- vault operator init -format=json | tee /tmp/vault-unseal-keys.json"
  register: vault_init_result

- name: Debug
  debug:
    var: vault_init_result
    verbosity: 2

- name: Get Vault unseal key to ansible executor host
  command: "kubectl cp vault/vault-0:/tmp/vault-unseal-keys.json /tmp/vault-unseal-keys.json"
  when: vault_init_result.stdout.find("unseal_keys_b64") != -1

- name: Fetch Vault unseal key file to ansible host
  fetch:
    src: /tmp/vault-unseal-keys.json
    dest: /home/{{ username_on_the_host.stdout }}/
    flat: yes

- name: Set Vault unseal key file mode
  file: 
    path: /home/{{ username_on_the_host.stdout }}/vault-unseal-keys.json
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: 0400
  delegate_to: localhost

- name: Delete Vault unseal key file from ansible executor
  file:
    path: /tmp/unseal-keys.json
    state: absent

- name: Get unseal key from output
  set_fact:
    root_token: "{{ vault_init_result.stdout | from_json | json_query('root_token') }}"
    unseal_key: "{{ vault_init_result.stdout | from_json | json_query('unseal_keys_b64') }}"