apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.user_namespace1.name }}
  labels: 
  {{- range $key, $value := .Values.user_namespace1.labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 