apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- range $key, $value := .Values.first_role.labels }}
    {{ $key }} : {{ $value }}
    {{- end }} 
  name: {{ .Values.first_role.name }}
  namespace: {{ .Values.first_role.namespace }}
rules:
{{- range  .Values.first_role.rules }}  {{- range $key, $value := . }}
{{- if eq $key "apiGroups" }}
- {{ $key }}
{{- else }}
  {{ $key }}
{{- end }}
{{- range $value }}
{{- if empty . }}
  - {{ . | toString | squote }}
{{- else }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end }} 
{{- end }}  