ansible_host: 192.168.1.131
ansible_user: vagrant
ansible_ssh_private_key_file: "./.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"


###################### Kubernetes variable ############################################
kubernetes_role: "first-master"
kubernetes_kubeproxy_mode: "ipvs"
kubernetes_apiserver_advertise_address: "{{ ansible_host }}"
kubernetes_cluster_domain_name: "cluster.local"
kubernetes_cgroupDriver: "systemd"
kubernetes_cri_socket: "/run/containerd/containerd.sock"
kubernetes_cluster_name: kubernetes
kubernetes_apiserver_certSANs:
  - 127.0.0.1
  - cluster-api.example.com
  - 192.168.1.131
  - 192.168.1.132
  - 192.168.1.133 
  
###################### Echo app variables #############################################
#Echo app chart name
chart_name_app: echo-app

#Echo app toleration
echo_app_taint: node-role.kubernetes.io/worker

#k8s cert-manager issuer CRD name 
issuer_name: echo.example.com-issuer

#k8s cert-manager certificate CRD name 
cert_name: echo.example.com-cert

#k8s secret name used by ingress
secret_name: echo-example-com-tls

#a common name to be used on the Certificate.
server_name: echo.example.com

#a list of DNS subjectAltNames to be set on the Certificate.
dns_server_name: echo.example.com

# Vault pki policy name.
pki_policy_name: example-dot-com

#k8s app namespace
k8s_namespace: namespace1

#Domain name used for certificate generation
domain_name: "example.com"

#Allowing subdomain in certificate
allow_subdomains: "true"

#Maximum certificate ttl
max_cert_ttl: "15m"

# Echo-app namespace users
chart_name_users: echo-app-users
k8s_users_namespace: "{{ k8s_namespace }}"
users:
  - username: echo-app-admin
    default_role: admin
  - username: echo-app-dev
    default_role: edit
    
########################### Cert-manager variables #####################################
# Cert-manager pod toleration
cert_manager_taint: node-role.kubernetes.io/worker

########################### Hashicorp Vault variables #####################################
#Root Certificate Authority name
root_ca_name: "Demo Root Certificate Authority"

#Root Certificate Authority certificate filename
root_ca_cert_filename: "demo-root-ca"

# Vault pod toleration
vault_taint: node-role.kubernetes.io/worker

########################### Cluster monitoring variables ##################################

monitoring_namespace: monitoring

#Kube-prometheus-stack pod toleration
prometheus_stack_taint: node-role.kubernetes.io/worker

########################### Cluster name ##################################################
elastic_operator_version: "1.6.0"
# Namespace for elastic-operator deploy
elastic_namespace: elastic-operator
# Elastic Operator pod toleration
elastic_operator_taint: node-role.kubernetes.io/worker

elastic_version: "7.10.0"
#Elasticsearch and kibana pod toleration
elastic_app_taint: node-role.kubernetes.io/worker
# Elasticsearch CRD name
elastic_name: elasticsearch
# Kibana CRD name
kibana_name: kibana
#Kibana instance number
kibana_count: 1
#Elasticsearch instance number
elastic_count: 1
# Elasticsearch and Kibana pod toleration
logging_namespace: logging

#Fluentbit pod toleration
fluentbit_toleration:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/gw
    effect: NoSchedule
  - key: node-role.kubernetes.io/worker
    effect: NoSchedu  

# Fluentbit config
fluentbit_service: |
  [SERVICE]
      Flush 1
      Daemon Off
      Log_Level info
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port {{ '{{' }} .Values.service.port {{ '}}' }}

## https://docs.fluentbit.io/manual/pipeline/inputs
fluentbit_inputs: |
  [INPUT]
      Name tail
      Path /var/log/containers/*.log
      Parser docker
      Tag kube.*
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On

  [INPUT]
      Name systemd
      Tag host.*
      Read_From_Tail On

## https://docs.fluentbit.io/manual/pipeline/filters
fluentbit_filter: |
  [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
## https://docs.fluentbit.io/manual/pipeline/outputs
fluentbit_output: |
  [OUTPUT]
      Name es
      Match kube.*
      Host minikube-logging-es-http.logging.svc
      HTTP_User elastic
      HTTP_Passwd {{ elastic_pass.stdout }}
      tls             On
      tls.verify      Off
      Logstash_Format On
      Retry_Limit False
      Trace_Error On
      Replace_Dots On

  [OUTPUT]
      Name es
      Match host.*
      Host minikube-logging-es-http.logging.svc
      HTTP_User elastic
      HTTP_Passwd {{ elastic_pass.stdout }}
      tls             On
      tls.verify      Off
      Logstash_Format On
      Logstash_Prefix node
      Retry_Limit False
      Trace_Error On
      Replace_Dots On
## https://docs.fluentbit.io/manual/pipeline/parsers
fluentbit_customParsers: |
  [PARSER]
      Name docker_no_time
      Format json
      Time_Keep Off
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L

  [PARSER]
      Name   nginx_custom
      Format regex
      Regex (?<remote_addr>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<request>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S %z
      
  [PARSER]
      Name   echo_app_parser
      Format regex
      Regex (?<log_time>[^\]]*) (?<servername>[^ ]*) (?<remote_addr>[^ ]*) "(?<method>\S+) (?<request>[^\"]*)" (?<code>[^ ]*) (?<size>[^ ]*) "(?<agent>[^\"]*)" (?<duration>[^ ]*)
      Time_Key log_time
      Time_Format %Y/%m/%d %H:%M:%S   