ansible_host: 192.168.1.131
ansible_user: vagrant
ansible_ssh_private_key_file: "./.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
kubernetes_kubeadm_init_extra_opts: "--upload-certs"

kubernetes_apiserver_advertise_address: "{{ ansible_host }}"
kubernetes_cluster_domain_name: "cluster.local"
kubernetes_cgroupDriver: "systemd"
kubernetes_cri_socket: "/run/containerd/containerd.sock"

kubernetes_role: "first-master"
kubernetes_kubeproxy_mode: "ipvs"
