# Default values for k8s_user.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_role_binding:
  - enabled: true
    name: "echo-app-CR"
    kind: User
    namespace: "namespace1"
    default_role: "view"
    rolename: "echo-app-admin"
    username: "echo-app-admin"
    sameAsRole: true
    labels:
      app: echo

cluster_roles:
  - enabled: false
    name: ""
    kind: ""
    namespace: ""
    labels: {}
    rules: []

#Example cluster_role    
# cluster_roles:
#   - enabled: false
#     name: "echo-app-admin"
#     kind: User
#     namespace: "namespace1"
#     labels: 
#       app: echo
#     rules:
#       - apiGroups:
#         - ''
#         resources:
#         - services
#         - endpoints
#         - nodes
#         - pods
#         - secrets
#         - configmaps
#         verbs:
#         - get
#         - list
#         - watch
#       - apiGroups:
#         - "extensions"
#         - "apps"
#         resources:
#         - deployments
#         - daemonsets
#         - statefulsets
#         - replicasets
#         verbs:
#         - get
#         - list
#         - watch
#       - apiGroups:
#         - networking.k8s.io
#         resources:
#         - ingresses
#         verbs:
#         - get
#         - list
#         - watch          
#   - enabled: false
#     name: "test_cr2"
#     kind: User
#     namespace: "namespace1"
#     labels: 
#       app: echo2
#     rules:
#       - apiGroups:
#         - ''
#         resources:
#         - services
#         - endpoints
#         - nodes
#         - pods
#         - secrets
#         - configmaps
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete
#       - apiGroups:
#         - "extensions"
#         - "apps"
#         resources:
#         - deployments
#         - daemonsets
#         - statefulsets
#         - replicasets
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete
#       - apiGroups:
#         - networking.k8s.io
#         resources:
#         - ingresses
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete

role_binding:
  - enabled: true
    name: "echo-app-admin-bind"
    kind: User
    namespace: "namespace1"
    default_role: "admin"
    rolename: "echo-app-admin"
    username: "echo-app-admin"
    labels:
      app: echo
  - enabled: true
    name: "echo-app-dev-bind"
    kind: User
    namespace: "namespace1"
    default_role: "edit"
    rolename: "echo-app-dev"
    username: "echo-app-dev"
    labels:
      app: echo

roles:
  - enabled: false
    name: ""
    kind: ""
    namespace: ""
    labels: {}
    rules: []

#Example role    
# roles:
#   - enabled: true
#     name: "echo-app-admin"
#     kind: User
#     namespace: "namespace1"
#     labels: 
#       app: echo
#     rules:
#       - apiGroups:
#         - ''
#         resources:
#         - services
#         - endpoints
#         - nodes
#         - pods
#         - secrets
#         - configmaps
#         verbs:
#         - get
#         - list
#         - watch
#       - apiGroups:
#         - "extensions"
#         - "apps"
#         resources:
#         - deployments
#         - daemonsets
#         - statefulsets
#         - replicasets
#         verbs:
#         - get
#         - list
#         - watch
#       - apiGroups:
#         - networking.k8s.io
#         resources:
#         - ingresses
#         verbs:
#         - get
#         - list
#         - watch          
#   - enabled: true
#     name: "echo-app-admin"
#     kind: User
#     namespace: "namespace1"
#     labels: 
#       app: echo
#     rules:
#       - apiGroups:
#         - ''
#         resources:
#         - services
#         - endpoints
#         - nodes
#         - pods
#         - secrets
#         - configmaps
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete
#       - apiGroups:
#         - "extensions"
#         - "apps"
#         resources:
#         - deployments
#         - daemonsets
#         - statefulsets
#         - replicasets
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete
#       - apiGroups:
#         - networking.k8s.io
#         resources:
#         - ingresses
#         verbs:
#         - get
#         - list
#         - watch
#         - create
#         - update
#         - patch
#         - delete